version: '3.3'

services:
  cu2_backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./src:/cu2_backend/src
    env_file:
      - ./.env

  cu2_database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'cu2'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'Asia/Seoul'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
  
  cu2_redis:
    image: redis:latest
    ports:
      - 6379:6379

